spring.application.name=sma
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/Student_Database
spring.datasource.username=postgres
spring.datasource.password=Yogiravi_2003
spring.jpa.show-sql=true
